const experienceDeck = [
  {
    id: "modern_isekai_self_insert",
    name: "现代人穿越代入",
    role: "玩家先以现实视角进入异世界，再被塞进新王身体，降低代入门槛。",
    timing: "开场第一幕",
  },
  {
    id: "goddess_blessing_pick",
    name: "女神外挂选择",
    role: "开局立刻给回档、魔眼、修炼三种爽文权能，先让玩家获得主动权。",
    timing: "穿越瞬间",
  },
  {
    id: "death_loop_pressure",
    name: "死亡回档压力",
    role: "借鉴轮回系体验，让失败保留情报、疼痛和攻略价值。",
    timing: "异世界教程",
  },
  {
    id: "training_growth_arc",
    name: "修炼成长曲线",
    role: "借鉴成长系体验，把魔法、剑术、礼法和人际都做成可升级技能。",
    timing: "异世界教程至中盘",
  },
  {
    id: "overpowered_crown_fantasy",
    name: "龙傲天王座爽点",
    role: "现代常识和外挂能力压制旧贵族，让审判、战场和恋爱都服务玩家成长。",
    timing: "全篇",
  },
  {
    id: "execution_clock",
    name: "倒计时处决",
    role: "开场三分钟内给玩家一个会死人、会失去证据的即时目标。",
    timing: "序章第一幕",
  },
  {
    id: "enemy_pet_mask",
    name: "敌国公主伪装成猫",
    role: "用萌点包住危险感，让玩家同时想保护、试探、占有情报。",
    timing: "序章至第一章",
  },
  {
    id: "bad_end_intel",
    name: "坏结局给情报",
    role: "借鉴轮回系 VN 的推进感，每个失败结局都揭开一块真相。",
    timing: "全篇",
  },
  {
    id: "phone_trigger_like",
    name: "密信触发器",
    role: "用书信、银铃、王印、梦境回声替代手机触发，制造选择与延迟后果。",
    timing: "第一章后",
  },
  {
    id: "closed_court_paranoia",
    name: "闭锁宫廷疑云",
    role: "把朝堂做成封闭村落式猜疑场，每个人都像盟友，也像凶手。",
    timing: "第一至第四章",
  },
  {
    id: "hero_identity_flip",
    name: "玩家身份翻转",
    role: "前期知道自己是现代穿越者，中盘发现塞德里克身体也藏着被切割的旧人格。",
    timing: "中点反转",
  },
  {
    id: "cute_scene_with_knife",
    name: "糖里藏刀",
    role: "每个亲密场景背后都有政治或记忆代价，避免纯日常泄气。",
    timing: "B 故事线",
  },
  {
    id: "map_of_lies",
    name: "谎言地图",
    role: "玩家用分支树回看已知谎言，形成推理和多周目动力。",
    timing: "第二章解锁",
  },
  {
    id: "trust_or_truth",
    name: "信任与真相互斥",
    role: "若急着查真相会伤害安塔莉亚，若只安抚她会错过证据。",
    timing: "关键选择",
  },
  {
    id: "public_mask_private_wound",
    name: "王座面具与私伤",
    role: "让宅男玩家扮演强势身份，同时在私密场景获得被理解的反馈。",
    timing: "全篇",
  },
  {
    id: "route_memory_carryover",
    name: "周目信息继承",
    role: "坏结局后保留梦痕、密语、CG 注释，推动二周目。",
    timing: "第二轮后",
  },
  {
    id: "romance_as_strategy",
    name: "恋爱也是策略",
    role: "亲近不能只当奖励按钮；它会改变盟友、审判和牺牲顺序。",
    timing: "全篇",
  },
  {
    id: "ally_with_agenda",
    name: "盟友各有目的",
    role: "所有配角都拥有独立意图，会在玩家犹豫时推进自己的计划。",
    timing: "全篇",
  },
  {
    id: "midpoint_false_victory",
    name: "中点假胜利",
    role: "玩家以为洗清战争真相，却发现真相本身是被设计出来的诱饵。",
    timing: "第六章",
  },
  {
    id: "all_is_lost_intimacy",
    name: "最低谷亲密",
    role: "政变后让玩家失去王位、失去猫形安塔莉亚，只剩彼此真实记忆。",
    timing: "第九章",
  },
  {
    id: "crownless_pressure",
    name: "失位压力连锁",
    role: "王位被夺后，让玩家在证人、人形、审判厅和记忆代价之间连选。",
    timing: "第九章",
  },
  {
    id: "trial_gauntlet",
    name: "审判攻防长链",
    role: "把公开审判做成二十四轮证据攻防，持续给目标、阻力和奖励。",
    timing: "第九章",
  },
  {
    id: "route_lock_finale",
    name: "终局路线锁定",
    role: "把人物欲望、伤口和面具做成可玩压力场，让选择成为结局。",
    timing: "终局前夜",
  },
  {
    id: "consequence_corridor",
    name: "终局后果回廊",
    role: "把旧选择带上下文回放，让结局入口前每段后果都被确认。",
    timing: "结局群前",
  },
  {
    id: "thirty_day_campaign",
    name: "三十日战役日历",
    role: "把蓝图拆成三十天可玩推进，每段都有目标、阻力、奖励和钩子。",
    timing: "第一章后",
  },
  {
    id: "day_night_dossiers",
    name: "昼夜双线档案",
    role: "补足三十日每条政治、亲密、梦审、暗线档案的上下文与代价。",
    timing: "三十日战役后",
  },
  {
    id: "crown_countdown",
    name: "王冠倒计时",
    role: "把三十夜拆成连续压力回合，每回合都给目标、阻力、回报和新火线。",
    timing: "昼夜双线后",
  },
  {
    id: "character_arc_ledger",
    name: "人物弧光账本",
    role: "让主要人物的欲望、伪装、伤口、背叛、转向和回报都变成可玩节点。",
    timing: "王冠倒计时后",
  },
  {
    id: "branch_locked_revelation",
    name: "路线锁真相",
    role: "不同结局开放不同幕后证据，驱动玩家追全结局。",
    timing: "结局群",
  },
  {
    id: "bad_code_cash_in",
    name: "失败暗号兑现",
    role: "把坏结局获得的仓号、敲法、黑蜡和白手套名单变成主线行动。",
    timing: "审判前夜",
  },
  {
    id: "cg_as_scene_reward",
    name: "CG 承担戏剧瞬间",
    role: "关键人物出场、亲密推进、坏结局、反转揭露都必须有 CG。",
    timing: "80 张 CG 清单",
  },
  {
    id: "final_choice_reframes_start",
    name: "终局重解释开场",
    role: "最后让玩家明白开场处决令、王印、金丝笼都是同一场仪式的碎片。",
    timing: "真结局",
  },
];

const characterArcs = [
  {
    id: "player",
    name: "现代玩家",
    desire: "用外挂能力在异世界活下去，并把王座变成自己的爽文起点。",
    wound: "现实里总被规则推着走，第一次拥有能改写局面的力量。",
    mask: "用吐槽和爽文经验掩饰刚穿越的恐惧。",
    arc: "从想靠外挂横推一切，到学会把每次胜利变成真正的责任。",
  },
  {
    id: "cedric",
    name: "塞德里克",
    desire: "夺回身体旧记忆，确认现代灵魂会把王国带向哪里。",
    wound: "十六岁被迫学会用冷酷保命，并被切走一段关键记忆。",
    mask: "把本能残响藏在现代玩家的决策背后。",
    arc: "从残留人格，到愿意把王冠交给能承担责任的人。",
  },
  {
    id: "antalia",
    name: "安塔莉亚",
    desire: "夺回被封的人形、救下猫族俘虏、找出灭国真凶。",
    wound: "亲眼看见王都焚毁，却不确定自己是否也参与了仪式。",
    mask: "用猫形沉默和尖锐敌意保护自尊。",
    arc: "从只想复仇，到选择把故国未来交给活人共同承担。",
  },
  {
    id: "general",
    name: "北境大将军",
    desire: "维持军权，阻止战争罪责反噬北境军。",
    wound: "曾在旧王都火海中救过孩子，却被迫背上屠城名声。",
    mask: "用粗暴忠诚掩盖恐惧。",
    arc: "从要求血债血偿，到承认军队也需要被审判。",
  },
  {
    id: "minister",
    name: "财政大臣",
    desire: "保住贵族秩序与自己的账册秘密。",
    wound: "少年时因饥荒失去家族，只相信账本和可交换的利益。",
    mask: "把所有善恶都说成国家成本。",
    arc: "可成为揭账盟友，也可成为十五结局之一的最终刽子手。",
  },
  {
    id: "scribe",
    name: "老书记官",
    desire: "让先王时代被抹掉的名字重新出现。",
    wound: "参与过第一次记忆切割仪式，余生都在补偿。",
    mask: "用温和旁观掩盖知情不报。",
    arc: "从记录者变成证人，最终用自己记忆补齐真相。",
  },
  {
    id: "maid",
    name: "侍女米拉",
    desire: "在宫廷夹缝中活下去，并保护被当成工具的小人物。",
    wound: "家人死于王都粮道断供。",
    mask: "绝对服从。",
    arc: "从递盘子的旁观者，到选择打开宫门的关键行动者。",
  },
  {
    id: "servant",
    name: "侍从卢卡",
    desire: "摆脱底层身份，成为能被王看见的人。",
    wound: "曾告发同伴换取入宫机会。",
    mask: "卑微勤快。",
    arc: "可被玩家拉回，也可因嫉妒投向政变线。",
  },
];

const saveTheCatBeats = [
  {
    id: "opening_image",
    chapter: "序章",
    targetMinutes: 12,
    purpose: "王城处决倒计时、金丝笼、王印证物同时出现。",
    playerNeed: "先判断自己要当怎样的国王。",
  },
  {
    id: "theme_stated",
    chapter: "序章",
    targetMinutes: 20,
    purpose: "真相死得太快，活人才有机会作证。",
    playerNeed: "理解杀伐果断与追真相并不总能兼得。",
  },
  {
    id: "setup",
    chapter: "第一章",
    targetMinutes: 90,
    purpose: "建立宫廷、战俘营、猫形安塔莉亚、三项核心数值。",
    playerNeed: "每五分钟获得一个新疑点或关系反馈。",
  },
  {
    id: "catalyst",
    chapter: "第二章",
    targetMinutes: 120,
    purpose: "密信证明王印来自未来周目，塞德里克的笔迹在上面。",
    playerNeed: "意识到自己可能已经经历过这三十日。",
  },
  {
    id: "debate",
    chapter: "第二章",
    targetMinutes: 150,
    purpose: "查账、安抚、诱敌三条路线互相排斥。",
    playerNeed: "开始为自己的玩法风格付代价。",
  },
  {
    id: "break_into_two",
    chapter: "第三章",
    targetMinutes: 180,
    purpose: "安塔莉亚月下现形，玩家正式进入共犯关系。",
    playerNeed: "从养成保护转向并肩破局。",
  },
  {
    id: "b_story",
    chapter: "第四章",
    targetMinutes: 300,
    purpose: "恋爱线与信任线开始影响政治线。",
    playerNeed: "亲密场景同时获得情报、危险和情绪回报。",
  },
  {
    id: "fun_and_games",
    chapter: "第五章",
    targetMinutes: 480,
    purpose: "宫廷狼人杀、战俘营调查、旧都潜入、梦境审讯轮替。",
    playerNeed: "持续解谜、收集坏结局线索、解锁 CG。",
  },
  {
    id: "midpoint",
    chapter: "第六章",
    targetMinutes: 600,
    purpose: "公开证据洗清安塔莉亚，却发现塞德里克是仪式容器。",
    playerNeed: "此前预期完全翻转。",
  },
  {
    id: "bad_guys_close_in",
    chapter: "第七至八章",
    targetMinutes: 780,
    purpose: "将军逼宫、大臣烧账、侍从背叛、书记官失忆。",
    playerNeed: "在多线压力中决定优先救谁、牺牲什么。",
  },
  {
    id: "all_is_lost",
    chapter: "第九章",
    targetMinutes: 960,
    purpose: "王位失去，安塔莉亚人形崩解，玩家路线进入结局锁定。",
    playerNeed: "用此前积累的信任和情报换最后一次机会。",
  },
  {
    id: "finale",
    chapter: "终章",
    targetMinutes: 1200,
    purpose: "审判、破咒、献祭、共治、放逐等结局群展开。",
    playerNeed: "让自己的选择成为结局，而非只看作者收束。",
  },
];

const branchPoints = [
  { id: "bp00_blessing", act: "穿越序章", question: "女神给的外挂，要回档、魔眼，还是修炼圣体？", options: ["回档王权", "全知魔眼", "修炼圣体"] },
  { id: "bp00_training", act: "异世界教程", question: "第一轮成长先读回档、练魔力，还是压贵族？", options: ["读回档", "练魔力", "压贵族"] },
  { id: "bp01_execution", act: "序章", question: "稳军心，还是保活口？", options: ["斩袭营者", "扣军令"] },
  { id: "bp02_proof", act: "第一章", question: "逼她暴露，还是暂时保护秘密？", options: ["逼她现形", "装作不知", "设铃试探"] },
  { id: "bp03_food", act: "第一章", question: "救战俘营，救王都粮仓，还是先抓内鬼？", options: ["开仓", "控粮", "钓饵"] },
  { id: "bp04_campaign", act: "三十日战役", question: "每日推进先问证人、压证物，还是护住她？", options: ["问证人", "压证物", "护她"] },
  { id: "bp05_dossier", act: "三十日档案", question: "昼夜档案先翻旧名、封证物，还是牵住她？", options: ["翻旧名", "封证物", "牵住她"] },
  { id: "bp06_countdown", act: "王冠倒计时", question: "每夜压力先压钟、换证，还是护名？", options: ["压钟", "换证", "护名"] },
  { id: "bp07_arc_ledger", act: "人物弧光账本", question: "人物弧光先认伤、拆谎，还是给路？", options: ["认伤", "拆谎", "给路"] },
  { id: "bp08_moon", act: "第三章", question: "月下真身被撞见时，靠近、退让、还是威胁？", options: ["逼问", "退后", "碰耳"] },
  { id: "bp09_contract", act: "第四章", question: "同盟是契约、握手，还是血誓？", options: ["立约", "伸手", "血誓"] },
  { id: "bp10_camp", act: "第五章", question: "先救活人还是先拿证据？", options: ["救营", "查账", "跟踪"] },
  { id: "bp11_wolf", act: "第五章", question: "宫廷狼人杀第一轮指认谁？", options: ["将军", "大臣", "侍从", "书记官"] },
  { id: "bp12_memory", act: "第六章", question: "恢复塞德里克记忆，还是先保安塔莉亚人形？", options: ["取回", "封住"] },
  { id: "bp13_lie_map", act: "第七章", question: "谎言地图第一枚钉子落在哪条证据上？", options: ["军令", "蜡封", "钥匙", "月相"] },
  { id: "bp14_trial_eve", act: "第八章", question: "天亮前兑现哪条失败暗号？", options: ["北门七", "王寝门", "礼官册", "黑蜡"] },
  { id: "bp15_court_tool", act: "第八章", question: "只能带一种筹码上庭，带证人、名单，还是先保她？", options: ["带证人", "带名单", "带她走"] },
  { id: "bp16_crownless", act: "第九章", question: "王位被夺后，先追药车、扶住她，还是夺厅门？", options: ["追药车", "扶住她", "夺厅门"] },
  { id: "bp17_red_page", act: "第九章", question: "红账末页要用谁的记忆作价？", options: ["王忆", "旧伤", "银铃"] },
  { id: "bp18_enter_trial", act: "第九章", question: "证据、人形和时间同时崩坏时，怎样入庭？", options: ["入庭", "补页", "扶她"] },
  { id: "bp19_trial_round", act: "第九章", question: "每轮证据攻防用哪种打法？", options: ["追名字", "压证物", "护证人"] },
  { id: "bp20_route_lock", act: "终局前夜", question: "每个人的伤口、面具和去路怎么处理？", options: ["接伤口", "拆面具", "给去路"] },
  { id: "bp21_consequence", act: "结局群前", question: "旧选择的后果如何进入分支树？", options: ["收证据", "稳人心", "开暗线"] },
  { id: "bp22_trial", act: "第九章", question: "公开真相，还是先保护证人？", options: ["公审", "密审", "逃离"] },
  { id: "bp23_coup", act: "第九章", question: "政变夜救王座、救她、救民众？", options: ["守殿", "追她", "开门"] },
  { id: "bp24_sacrifice", act: "第九章", question: "谁承受记忆回流？", options: ["塞德里克", "安塔莉亚", "书记官"] },
  { id: "bp25_exile", act: "第九章", question: "失去王位后回宫，还是去旧都？", options: ["回宫", "旧都", "北境"] },
  { id: "bp26_final_ritual", act: "终章", question: "破咒方式决定人、国、记忆的取舍。", options: ["王血", "猫印", "双魂"] },
  { id: "bp27_gate", act: "终章", question: "终局之后留下、远走、或重启周目？", options: ["留下", "远走", "重启"] },
];

const endings = [
  { id: "e01_white_cat_pact", type: "true", title: "白猫之约", requirement: "亲近、观察、证据三线均完整。" },
  { id: "e02_iron_crown", type: "normal", title: "铁王冠", requirement: "高警戒低亲近，保住国家失去安塔莉亚。" },
  { id: "e03_cat_queen", type: "normal", title: "猫王女复国", requirement: "选择旧都与猫印，塞德里克退位。" },
  { id: "e04_shared_throne", type: "gold", title: "双王座", requirement: "公审成功且政变夜三方幸存。" },
  { id: "e05_burned_ledger", type: "bad", title: "烧毁的账册", requirement: "忽视财政线。" },
  { id: "e06_silent_cage", type: "bad", title: "沉默金笼", requirement: "高控制低信任。" },
  { id: "e07_northern_blade", type: "bad", title: "北境刀声", requirement: "连续让军方坐大。" },
  { id: "e08_empty_bed", type: "bad", title: "空床", requirement: "亲密线断裂后强行追查。" },
  { id: "e09_white_trial", type: "normal", title: "白色审判", requirement: "公审真相但牺牲书记官记忆。" },
  { id: "e10_luca_key", type: "bad", title: "侍从的钥匙", requirement: "无视卢卡嫉妒。" },
  { id: "e11_mira_gate", type: "normal", title: "米拉开的门", requirement: "救小人物线完整。" },
  { id: "e12_moonless", type: "bad", title: "无月夜", requirement: "月相触发失败。" },
  { id: "e13_old_capital_snow", type: "normal", title: "旧都落雪", requirement: "放弃王都，保留两人记忆。" },
  { id: "e14_loop_zero", type: "meta", title: "第零周目", requirement: "收集全部坏结局情报。" },
  { id: "e15_goodbye_king", type: "normal", title: "再见，国王", requirement: "远走结局，国家由议会接管。" },
  { id: "e16_black_sun", type: "bad", title: "黑日", requirement: "仪式被幕后者夺取。" },
];

const cgPlan = [
  "cg001_execution_square",
  "cg002_throne_cage",
  "cg003_cat_royal_seal",
  "cg004_soft_order",
  "cg005_open_cage",
  "cg006_bedroom_watch",
  "cg007_pillow_seal",
  "cg008_silver_bell",
  "cg009_breakfast_pressure",
  "cg010_fountain_kitten",
  "cg011_council_map",
  "cg012_evening_fable",
  "cg013_moon_corridor",
  "cg014_human_reveal",
  "cg015_library_spell",
  "cg016_library_confrontation",
  "cg017_truce_hand",
  "cg018_refugee_camp",
  "cg019_hidden_granary",
  "cg020_archive_ledger",
  "cg021_burned_account",
  "cg022_wolf_table",
  "cg023_general_duel",
  "cg024_minister_smile",
  "cg025_scribe_memory",
  "cg026_mira_gate",
  "cg027_luca_key",
  "cg028_old_capital_gate",
  "cg029_old_capital_snow",
  "cg030_altar_memory",
  "cg031_child_cedric",
  "cg032_child_antalia",
  "cg033_false_victory",
  "cg034_public_trial",
  "cg035_secret_trial",
  "cg036_witness_poison",
  "cg037_palace_coup",
  "cg038_northern_army",
  "cg039_burning_library",
  "cg040_infirmary_aftermath",
  "cg041_collapsed_human_form",
  "cg042_exile_road",
  "cg043_north_watchtower",
  "cg044_memory_flood",
  "cg045_scribe_sacrifice",
  "cg046_cat_mark_awakens",
  "cg047_king_blood_ritual",
  "cg048_dual_soul_ritual",
  "cg049_black_sun",
  "cg050_silent_cage_end",
  "cg051_iron_crown_end",
  "cg052_cat_queen_end",
  "cg053_shared_throne_end",
  "cg054_white_cat_pact_end",
  "cg055_loop_zero_end",
  "cg056_empty_bed_end",
  "cg057_mira_gate_end",
  "cg058_old_capital_snow_end",
  "cg059_goodbye_king_end",
  "cg060_moonless_end",
  "cg061_northern_blade_end",
  "cg062_luca_key_end",
  "cg063_white_trial_end",
  "cg064_burned_ledger_end",
  "cg065_private_tears",
  "cg066_first_touch",
  "cg067_wound_binding",
  "cg068_rooftop_moon",
  "cg069_secret_letter",
  "cg070_court_mask_ball",
  "cg071_poisoned_tea",
  "cg072_cell_confession",
  "cg073_rain_escape",
  "cg074_hidden_catacomb",
  "cg075_future_seal",
  "cg076_broken_bell",
  "cg077_living_witnesses",
  "cg078_dead_witnesses",
  "cg079_crown_removed",
  "cg080_hand_at_gate",
  "cg081_dawn_council",
  "cg082_memory_tree",
  "cg083_last_restart",
  "cg084_after_story",
];

const productionTargets = {
  intendedPlayHours: 20,
  targetChineseChars: 180000,
  minimumBranchPoints: 10,
  plannedBranchPoints: branchPoints.length,
  minimumEndings: 15,
  plannedEndings: endings.length,
  minimumCg: 80,
  plannedCg: cgPlan.length,
  minimumExperienceHooks: 15,
  plannedExperienceHooks: experienceDeck.length,
};

const funCheckpoints = [
  {
    id: "first_60_seconds",
    promise: "一分钟内给处决倒计时、证物、敌国公主三个钩子。",
    playerQuestion: "我到底该先稳住国家，还是救下能证明真相的人？",
    failCondition: "如果玩家只是在看人物介绍，这段必须重写。",
  },
  {
    id: "choice_has_cost",
    promise: "每个关键选项同时给收益和代价，且下一段立刻兑现。",
    playerQuestion: "我愿意为了眼前目标失去哪一种长期优势？",
    failCondition: "如果出现显然正确的按钮，这个选项组不能验收。",
  },
  {
    id: "every_scene_goal",
    promise: "每场戏至少有一个即时目标、一个阻力、一个信息奖励。",
    playerQuestion: "我现在点击下一句，是为了得到什么？",
    failCondition: "如果连续三句只在解释背景，这场戏必须拆掉或改成行动。",
  },
  {
    id: "character_agency",
    promise: "具名人物都有自己的目的，会在玩家不管时主动推进。",
    playerQuestion: "我能相信谁？如果放着不管，他会做什么？",
    failCondition: "如果角色只负责递台词或服务主角，这条人物线不能验收。",
  },
  {
    id: "reversal_cadence",
    promise: "每 20 到 30 分钟有一次足以改写玩家预期的发现。",
    playerQuestion: "刚才的真相会不会也是别人设计给我看的？",
    failCondition: "如果章节结束时玩家对下一章没有新问题，这章不能验收。",
  },
  {
    id: "bad_end_reward",
    promise: "坏结局必须给新情报、新 CG 或新路线暗号。",
    playerQuestion: "我失败了，但下一轮知道了什么？",
    failCondition: "如果坏结局只是惩罚，删掉或补情报奖励。",
  },
  {
    id: "bad_code_payoff",
    promise: "失败暗号要在主线里兑现，玩家能亲手把失败变成突破。",
    playerQuestion: "上一轮死出来的线索，这次能打开哪扇门？",
    failCondition: "如果暗号只停在结局文本里，这段不能验收。",
  },
  {
    id: "romance_pressure",
    promise: "恋爱进展会改变政治和推理，而不只是加好感。",
    playerQuestion: "我靠近她，是安慰、利用，还是把自己也交出去？",
    failCondition: "如果亲密场景不影响后续分支，它不能算主线场景。",
  },
  {
    id: "market_vn_pacing",
    promise: "开场强钩子、中段连环反转、终盘路线收束都按商业 VN 节奏推进。",
    playerQuestion: "我已经猜错了一次，还想继续猜第二次。",
    failCondition: "如果故事脉络没有偏离开局预期，终盘不准验收。",
  },
];

export const longformPlan = {
  productionTargets,
  experienceDeck,
  characterArcs,
  saveTheCatBeats,
  branchPoints,
  endings,
  cgPlan,
  funCheckpoints,
};
